---
- name: Converge
  hosts: all
  gather_facts: true
  roles:
  - {
  role: mattwillsher.mysql,
  version: 10.1,
  mysql_installation_source: 'mariadb',
  root_password: 'mysuperpassword',
  mysql_databases: [{ name: 'mydb1'}, {name: 'mydb2' }]
  }
